application: truemusic-144108
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /css
  static_dir: css
  
- url: /form.php
  script: form.php
  
- url: .*
  script: main.php